//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "NSObject.h"

@protocol DTFileSystemEventStreamDelegate <NSObject>
- (void)fileSystemEventStream:(id)arg1 notedChangeAtPath:(id)arg2 scanRecursively:(BOOL)arg3;

@optional
- (void)historyWrappedForFileSystemEventStream:(id)arg1;
- (void)historyCompleteForFileSystemEventStream:(id)arg1;
- (void)fileSystemEventStream:(id)arg1 notedVolumeUnmount:(id)arg2;
- (void)fileSystemEventStream:(id)arg1 notedVolumeMount:(id)arg2;
- (void)fileSystemEventStream:(id)arg1 notedChangeOfRootPath:(id)arg2;
@end

