//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import "NSAppleEventDescriptor.h"

@interface NSAppleEventDescriptor (PBXFoundationExtensions)
+ (id)documentDescriptorFromFilename:(id)arg1;
+ (id)fileDescriptorFromPath:(id)arg1;
- (id)sendAppleEventAndWaitForReply;
- (id)sendAppleEventAndWaitForReplyForTicks:(long long)arg1;
- (long long)send;
- (id)descriptionAtIndentLevel:(long long)arg1;
- (id)hierarchicalDescription;
@end

