//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "NSArray.h"

@interface NSArray (XCPropertyValueAdditions)
- (id)propertyValueDebugDescription;
- (id)valueByApplyingOperator:(id)arg1 inContext:(id)arg2;
- (id)evaluateAsArrayInContext:(id)arg1;
- (id)evaluateAsArrayInContext:(id)arg1 withNestingState:(const void *)arg2;
- (id)evaluateAsStringInContext:(id)arg1;
- (id)evaluateAsStringInContext:(id)arg1 withNestingState:(const void *)arg2;
@end

