//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <DevToolsCore/PBXNativeTarget.h>

@interface PBXAggregateTarget : PBXNativeTarget
{
}

+ (id)standardBuildPhaseClasses;
+ (id)targetTypeDisplayName;
+ (id)categorizedTargetName;
- (id)productReferenceExpectedFileTypeForConfigurationNamed:(id)arg1;
- (BOOL)productReferenceIsExecutable;
- (id)relevantToolSpecifications;
- (id)relevantToolSpecificationsForConfigurationsNamed:(id)arg1;
- (id)relevantToolSpecificationsForConfigurationNamed:(id)arg1;
- (BOOL)isAggregate;
- (BOOL)canPackageHeaders;
- (BOOL)canInstallHeaders;
- (BOOL)wantsProductSettings;
- (BOOL)hasUserConfigurableBuildRules;
- (id)buildSettingsPanes;
- (id)defaultProductTypeIdentifierByAnalyzingConfiguration;

@end

