//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import "NSObject.h"

@class PBXBTree;

@interface PBXBTreeEnumerator : NSObject
{
    PBXBTree *_btree;
    _pbxbtreecursor_4f04ce2b _cursor;
}

- (const void *)previousValue;
- (const void *)nextValueForKey:(const void *)arg1;
- (const void *)nextValue;
- (const void *)valueForKey:(const void *)arg1;
- (const void *)lastValue;
- (const void *)firstValue;
- (id)initWithBTree:(id)arg1;

@end

