//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <DevToolsCore/XCProductTypeSpecification.h>

@interface PBXBundleProductType : XCProductTypeSpecification
{
}

- (id)computeProductTouchActionInTargetBuildContext:(id)arg1;
- (void)defineAuxiliaryFilesInTargetBuildContext:(id)arg1;
- (void)computeProductDependenciesInTargetBuildContext:(id)arg1;
- (id)linkerSpecificationForObjectFilesInTargetBuildContext:(id)arg1;

@end

