//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import <DevToolsCore/PBXBookmarkItem.h>

@class NSMutableArray;

@interface PBXBookmarkGroup : PBXBookmarkItem
{
    NSMutableArray *_children;
}

+ (id)archivableRelationships;
- (void)awakeFromPListUnarchiver:(id)arg1;
- (id)readFromPListUnarchiver:(id)arg1;
- (BOOL)shouldArchiveChildren;
- (id)childrenBookmarksForFilename:(id)arg1;
- (id)childrenBookmarksForFileReference:(id)arg1;
- (BOOL)acceptsChild:(id)arg1;
- (BOOL)isAncestorOfChild:(id)arg1;
- (void)removeChild:(id)arg1;
- (void)addChild:(id)arg1;
- (void)insertChildren:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)_setChildrensContainer:(id)arg1;
- (void)_setChildren:(id)arg1;
- (id)children;
- (void)setBookmarkGroup:(id)arg1;
- (void)setContainer:(id)arg1;
- (void)dealloc;
- (id)initWithName:(id)arg1;

@end

