//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import <DevToolsCore/PBXBuildPhase.h>

@class NSString;

@interface PBXCopyFilesBuildPhase : PBXBuildPhase
{
    int _dstSubfolderSpec;
    NSString *_dstPath;
}

+ (id)archivableAttributes;
+ (id)defaultName;
+ (id)identifier;
- (Class)dependencyGraphSnapshotClass;
- (BOOL)acceptsVariantGroups;
- (void)awakeFromPListUnarchiver:(id)arg1;
- (id)allowedFileTypes;
- (void)setSubpath:(id)arg1 relativeToSubfolder:(int)arg2;
- (void)setAbsolutePath:(id)arg1;
- (id)destinationPath;
- (int)destinationSubfolder;
- (BOOL)canRename;
- (void)dealloc;
- (id)initWithName:(id)arg1;
- (id)initFromTemplateDictionary:(id)arg1;
- (void)setAppleScriptDestinationSubfolder:(unsigned int)arg1;
- (unsigned int)appleScriptDestinationSubfolder;
- (void)setDestinationPath:(id)arg1;
- (void)setDestinationSubfolder:(int)arg1;

@end

