//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import <DevToolsCore/PBXCCScope.h>

@class PBXMemberContainerSymbol;

@interface PBXCCMethodScope : PBXCCScope
{
    PBXMemberContainerSymbol *_containerSymbol;
    BOOL _isInstance;
}

+ (id)methodScopeWithSymbol:(id)arg1 isInstanceMethod:(BOOL)arg2;
- (void)addSymbolsToArray:(id)arg1;
- (id)getSymbolWithName:(id)arg1;
- (void)addSymbol:(id)arg1;
- (id)containerSymbol;
- (BOOL)isInstance;
- (id)description;
- (void)dealloc;
- (id)initWithSymbol:(id)arg1 isInstanceMethod:(BOOL)arg2;

@end

