//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import <DevToolsCore/PBXObject.h>

#import "PBXChangeNotification.h"

@class NSMutableDictionary, NSString;

@interface PBXContainerItem : PBXObject <PBXChangeNotification>
{
    NSString *_comments;
    NSMutableDictionary *_uiContext;
}

+ (id)archiveNameForKey:(id)arg1;
+ (id)archivableUserAttributes;
+ (id)archivableAttributes;
- (BOOL)shouldArchiveUserInterfaceContext;
- (BOOL)shouldArchiveComments;
- (void)removeObjectForUserInterfaceContextKey:(id)arg1;
- (void)setObject:(id)arg1 forUserInterfaceContextKey:(id)arg2;
- (id)objectForUserInterfaceContextKey:(id)arg1;
- (void)setUserInterfaceContext:(id)arg1;
- (id)userInterfaceContext;
- (void)willChangeWithArchivePriority:(int)arg1;
- (void)willChange;
- (int)changeMask;
- (void)setContainer:(id)arg1;
- (id)container;
- (void)setProject:(id)arg1;
- (id)project;
- (id)comments;
- (void)setComments:(id)arg1;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)arg1 getUnretainedObjectMappings:(id *)arg2;
- (id)init;
- (void)handleMoveCommand:(id)arg1;

@end

