//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import <DevToolsCore/PBXMemberContainerSymbol.h>

@interface PBXCategorySymbol : PBXMemberContainerSymbol
{
}

+ (BOOL)canRepresentSymbolType:(int)arg1;
- (id)instanceVariablesIncludingInherited:(BOOL)arg1 matchingName:(id)arg2 usingStyle:(int)arg3;
- (id)instanceVariablesIncludingInherited:(BOOL)arg1;
- (id)classVariablesIncludingInherited:(BOOL)arg1 matchingName:(id)arg2 usingStyle:(int)arg3;
- (id)classVariablesIncludingInherited:(BOOL)arg1;
- (id)allVariablesIncludingInherited:(BOOL)arg1 matchingName:(id)arg2 usingStyle:(int)arg3;
- (id)allVariablesIncludingInherited:(BOOL)arg1;
- (id)symbolsOfType:(int)arg1 includingInherited:(BOOL)arg2;
- (id)symbolsOfType:(int)arg1 includingInherited:(BOOL)arg2 matchingName:(id)arg3 usingStyle:(int)arg4;
- (id)baseClassSymbol;
- (id)helpMarkerSymbolType;
- (id)typeString;
- (id)displayNameIncludingClassInfo:(BOOL)arg1;

@end

