//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import <DevToolsCore/PBXMemberContainerSymbol.h>

@interface PBXClassSymbol : PBXMemberContainerSymbol
{
}

+ (BOOL)canRepresentSymbolType:(int)arg1;
- (id)extensions;
- (id)categories;
- (BOOL)canHaveCategories;
- (id)superclassesIncludingIndirect:(BOOL)arg1;
- (id)allSuperclasses;
- (id)immediateSuperclasses;
- (id)subclassesIncludingIndirect:(BOOL)arg1;
- (id)helpMarkerSymbolValue;
- (id)helpMarkerSymbolType;
- (id)typeString;
- (id)displayNameIncludingClassInfo:(BOOL)arg1;

@end

