//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import <DevToolsCore/PBXSourceScanner.h>

@interface PBXCSourceScanner : PBXSourceScanner
{
    long long _class;
    long long _template;
    long long _operator;
    long long _interface;
    long long _implementation;
    long long _protocol;
    long long _end;
    long long _typedef;
    long long _throw;
    long long _import;
    long long _include;
    long long _define;
    long long _warning;
    long long _error;
    long long _pragma;
    long long _mark;
    long long _task;
    long long _sub;
    BOOL _isObjC;
    BOOL _isCPP;
    BOOL _isNQC;
}

- (id)parse;
- (void)initInterestingSymbols;

@end

