//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import <DevToolsCore/PBXBuildPhase.h>

@interface PBXFrameworksBuildPhase : PBXBuildPhase
{
}

+ (id)allowedFileTypes;
+ (id)defaultName;
+ (id)identifier;
- (Class)dependencyGraphSnapshotClass;
- (id)primaryAttributeForBuildFile:(id)arg1;
- (BOOL)insertBuildFiles:(id)arg1 atIndex:(unsigned long long)arg2;
- (id)_pathUsingLibraryDirectoryVariableForPath:(id)arg1;
- (id)_libraryFileExtensions;
- (id)_implicitLibrarySearchPaths;
- (id)_implicitFrameworkSearchPaths;
- (void)findFeaturesInUseAndAddToSet:(id)arg1 usingPathPrefix:(id)arg2;

@end

