//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import "NSObject.h"

@class NSMutableArray, NSString;

@interface PBXFileTypePart : NSObject
{
    NSString *_identifier;
    PBXFileTypePart *_superpart;
    NSMutableArray *_subparts;
}

+ (id)fileTypePartFromSpecificationArray:(id)arg1 identifier:(id)arg2;
- (BOOL)isSymbolicLink;
- (BOOL)isFolder;
- (BOOL)isPlainFile;
- (id)subparts;
- (void)setSuperpart:(id)arg1;
- (id)superpart;
- (id)identifier;
- (void)dealloc;
- (id)init;
- (id)initFromSpecificationArray:(id)arg1 identifier:(id)arg2;

@end

