//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class PBXObject;

@interface PBXGlobalID : NSObject <NSCopying>
{
    unsigned char _bytes[12];
    PBXObject *_theObject;
}

+ (void)initialize;
+ (void)setCachesHexStrings:(BOOL)arg1;
- (void)setRepresentedObject:(id)arg1;
- (id)representedObject;
- (id)description;
- (id)hexString;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)initWithHexString:(id)arg1;
- (id)init;
- (void)_cacheHexString:(id)arg1;
- (id)_cachedHexString;

@end

