//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary;

@interface PBXIndexedFileList : NSObject
{
    NSMutableArray *_indexedPaths;
    NSMutableDictionary *_indexSettings;
}

- (id)indexSettingForKey:(id)arg1;
- (void)setIndexSetting:(id)arg1 forKey:(id)arg2;
- (void)addIndexedPath:(id)arg1;
- (id)indexSettings;
- (id)indexedPaths;
- (void)setCommandLineArguments:(id)arg1;
- (id)commandLineArguments;
- (void)addFrameworkSearchPath:(id)arg1;
- (id)frameworkSearchPaths;
- (void)addHeaderSearchPath:(id)arg1;
- (id)headerSearchPaths;

@end

