//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import <DevToolsCore/PBXIndexingEngine.h>

@class JKZipFileStore, NSString;

@interface PBXJavaLanguageEngine : PBXIndexingEngine
{
    JKZipFileStore *_zipFile;
    NSString *_zipFileName;
    BOOL _stopped;
}

+ (id)indexableFileTypes;
+ (void)initialize;
- (void)stopIndexing;
- (void)indexFileAtAbsolutePath:(id)arg1 withSettings:(id)arg2;
- (id)dataForSourceFile:(id)arg1 inZipFile:(id)arg2;
- (void)dealloc;
- (void)releaseCachedData;

@end

