//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <DevToolsCore/PBXSourceScanner.h>

@interface PBXPythonSourceScanner : PBXSourceScanner
{
    long long _def;
    long long _class;
}

- (id)parse;
- (unsigned long long)_indentLevelForWhitespace:(id)arg1;
- (void)initInterestingSymbols;

@end

