//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import "NSObject.h"

@interface PBXSymbolUtilities : NSObject
{
}

+ (id)placeholderForString:(id)arg1;
+ (id)symbolsFromArray:(id)arg1 matchingName:(id)arg2 usingStyle:(int)arg3;
+ (id)uniqueMembersFromArray:(id)arg1;
+ (id)sortSymbolArray:(id)arg1 usingStyle:(int)arg2;

@end

