//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <DevToolsCore/PBXIndexEntry.h>

@interface PBXTypeDescriptor : PBXIndexEntry
{
}

+ (id)typeDescriptorForLocation:(union _pbxsymbollocation)arg1 projectIndex:(id)arg2;
- (id)description;
- (id)declarationForToken:(char *)arg1;
- (BOOL)isReferenceToken:(char *)arg1;
- (const char *)stringForToken:(char *)arg1;
- (char *)nextToken:(char *)arg1;
- (char *)firstToken;
- (struct _pbxtypedesc *)typeRecord;

@end

