//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "NSObject.h"

#import "XCFileSystemWatcherRegisteredObject.h"

@class PBXBuildFile;

@interface PBXTargetBuildPhaseFileSystemObserver : NSObject <XCFileSystemWatcherRegisteredObject>
{
    PBXBuildFile *_buildFile;
}

- (void)fileSystemWatcher:(id)arg1 notedChangeAtPath:(id)arg2 scanRecursively:(BOOL)arg3;
- (void)fileSystemWatcherWillClose:(id)arg1;
- (void)dealloc;
- (id)initWithBuildFile:(id)arg1;

@end

