//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import <DevToolsCore/PBXGroup.h>

@interface PBXVariantGroup : PBXGroup
{
}

+ (id)referenceByUnwrappingVariantGroup:(id)arg1;
+ (id)variantGroupByWrappingReference:(id)arg1 isLocalized:(BOOL)arg2;
+ (void)_replaceBuildFilesForReference:(id)arg1 withBuildFilesForReference:(id)arg2;
- (void)pruneReferencesBySendingBooleanSelector:(SEL)arg1 toObject:(id)arg2 withContext:(void *)arg3;
- (id)referencesForBuilding;
- (BOOL)makeVariantForRegion:(id)arg1;
- (BOOL)makeGlobal;
- (BOOL)makeLocalized;
- (id)variantForRegion:(id)arg1;
- (BOOL)ensureHasDefaultReference;
- (id)defaultReference;
- (BOOL)setName:(id)arg1 syncDisk:(BOOL)arg2;
- (BOOL)deleteFromProjectAndDisk:(BOOL)arg1;
- (BOOL)allowsRemovalFromDisk;
- (void)removeItem:(id)arg1;
- (id)destinationGroupForInsertion;
- (BOOL)isVariantGroup;
- (id)copyWithZone:(struct _NSZone *)arg1 getUnretainedObjectMappings:(id *)arg2;

@end

