//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <DevToolsCore/PBXJambaseTarget.h>

@interface PBXWrappedTarget : PBXJambaseTarget
{
}

+ (id)targetTypeDisplayName;
- (BOOL)canPackageHeaders;
- (id)fullProductName;
- (id)fullProductNameForConfigurationNamed:(id)arg1;
- (void)setWrapperPathExtension:(id)arg1;
- (id)wrapperPathExtension;
- (id)wrapperPathExtensionForConfigurationNamed:(id)arg1;
- (id)productNameForConfigurationNamed:(id)arg1;
- (id)productReferenceExpectedFileTypeForConfigurationNamed:(id)arg1;
- (id)defaultProductTypeIdentifierByAnalyzingConfiguration;

@end

