//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import "NSObject.h"

#import "NSPortDelegate.h"

@class NSCountedSet, NSMutableArray, NSMutableDictionary, NSPort;

@interface SCMManager : NSObject <NSPortDelegate>
{
    NSMutableArray *_logEntries;
    NSMutableArray *_activities;
    NSMutableArray *_startedRequests;
    NSMutableArray *_finishedRequests;
    NSMutableArray *_finishedActivities;
    NSMutableArray *_repositories;
    NSMutableArray *_repositoryNames;
    NSMutableDictionary *_repositoryClasses;
    id _messageHandler;
    NSPort *_responseAvailableNotificationPort;
    NSCountedSet *_addedRunLoopModes;
}

+ (id)sharedInstance;
@property(retain) NSMutableArray *repositoryNames; // @synthesize repositoryNames=_repositoryNames;
- (void)reportActivityFinished:(id)arg1;
- (void)reportRequestFinished:(id)arg1;
- (void)reportRequestStarted:(id)arg1;
- (void)reportLogEntry:(id)arg1;
- (void)reportActivity:(id)arg1;
- (void)handlePortMessage:(id)arg1;
- (id)repositoryRecommendedForPath:(id)arg1;
- (id)uniquedRepositoryName:(id)arg1;
- (void)removeRepository:(id)arg1;
- (void)addRepository:(id)arg1;
- (void)writeRepositoryDefaults;
- (id)repositories;
- (id)repositoryWithName:(id)arg1;
- (void)removeSandbox:(id)arg1;
- (id)sandboxForPath:(id)arg1 repository:(id)arg2;
- (void)removeRunLoopMode:(id)arg1;
- (void)addRunLoopMode:(id)arg1;
- (void)reportSCMMessage:(id)arg1 title:(id)arg2 completionCode:(int)arg3;
- (void)registerMessageHandler:(id)arg1;
- (id)repositoryClasses;
- (void)registerRepositoryClassName:(id)arg1 forSystemNamed:(id)arg2;
- (void)dealloc;
- (void)tearDown;
- (id)init;

@end

