//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import "NSObject.h"

#import "NSCopying.h"

@class SCMModel;

@interface SCMObject : NSObject <NSCopying>
{
    SCMObject *_parent;
    SCMModel *_model;
}

@property SCMObject *parent; // @synthesize parent=_parent;
@property SCMModel *model; // @synthesize model=_model;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)initWithModel:(id)arg1 parent:(id)arg2;

@end

