//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import <DevToolsCore/SCMSandboxEntry.h>

@class SCMSandboxOwner;

@interface SCMSandboxOwnerRoot : SCMSandboxEntry
{
    SCMSandboxOwner *_owner;
}

@property(retain) SCMSandboxOwner *owner; // @synthesize owner=_owner;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)disconnectSandbox:(id)arg1;
- (void)addSandbox:(id)arg1;
- (id)flattenedInterestingChildren;
- (id)interestingChildren;
- (id)childForPath:(id)arg1;
- (id)children;
- (BOOL)multipleRoots;

@end

