//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface XCAppleScriptBuildSetting : NSObject
{
    NSString *_name;
    NSString *_tempValue;
    id _container;
}

- (id)objectSpecifier;
- (void)setValue:(id)arg1;
- (id)value;
- (void)setContainer:(id)arg1;
- (id)container;
- (void)setName:(id)arg1;
- (id)name;
- (void)dealloc;
- (id)initWithName:(id)arg1 andContainer:(id)arg2;
- (id)init;

@end

