//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "NSObject.h"

@class PBXFileReference, XCSCMRevisionInfo;

@interface XCAppleScriptSCMRevision : NSObject
{
    PBXFileReference *_fileReference;
    XCSCMRevisionInfo *_revisionEntry;
}

- (id)objectSpecifier;
- (id)commitMessage;
- (id)timestamp;
- (id)author;
- (id)tagName;
- (id)revision;
- (id)name;
- (id)fileReference;
- (void)dealloc;
- (id)initWithFileReference:(id)arg1 revisionData:(id)arg2;

@end

