//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import "NSObject.h"

@class NSSet, NSString;

@interface XCArchiveFormat : NSObject
{
    NSString *_identifier;
    NSString *_minimumVersionSupported;
    unsigned long long _versionNumberForArchiver;
    NSSet *_supportedFeatures;
    NSSet *_archivingTranslations;
}

- (long long)compare:(id)arg1;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)versionNumberForArchiver;
- (id)displayName;
- (id)identifier;
- (id)minimumVersionSupportedName;
- (id)archivingTranslations;
- (id)supportedFeatures;
- (void)dealloc;
- (id)initWithArchiverVersion:(unsigned long long)arg1 identifier:(id)arg2 minimumVersionSupportedName:(id)arg3 supportedFeatures:(id)arg4 archivingTranslations:(id)arg5;
- (id)init;

@end

