//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import "NSObject.h"

@class NSArray, NSDate, NSMutableDictionary, NSString, NSURL;

@interface XCArchivedApplicationBuild : NSObject
{
    NSMutableDictionary *_archiveInfo;
    NSURL *_archiveURL;
    NSString *_uuid;
    NSString *_buildStatus;
}

+ (id)keyPathsForValuesAffectingBuildStatus;
+ (id)keyPathsForValuesAffectingDisplayedStatus;
+ (id)keyPathsForValuesAffectingValidationErrors;
+ (id)keyPathsForValuesAffectingUserProvidedComment;
+ (id)keyPathsForValuesAffectingUserProvidedName;
+ (id)keyPathsForValuesAffectingPlatformDisplayName;
+ (id)keyPathsForValuesAffectingArchivedDate;
+ (id)keyPathsForValuesAffectingApplicationVersion;
+ (id)keyPathsForValuesAffectingBundleIdentifier;
+ (id)keyPathsForValuesAffectingInfoPlist;
+ (id)keyPathsForValuesAffectingContainedApplicationURL;
+ (id)keyPathsForValuesAffectingPlatformIdentifier;
+ (id)keyPathsForValuesAffectingApplicationName;
+ (id)keyPathsForValuesAffectingArchiveInfoURL;
+ (id)archivedApplicationBuildWithContentsOfURL:(id)arg1;
@property(copy) NSString *uuid; // @synthesize uuid=_uuid;
@property(copy) NSURL *archiveURL; // @synthesize archiveURL=_archiveURL;
@property(retain) NSMutableDictionary *archiveInfo; // @synthesize archiveInfo=_archiveInfo;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)hash;
- (_Bool)usingFallbackClass;
- (id)description;
- (void)setBuildStatus:(id)arg1;
@property(readonly) NSString *buildStatus;
- (id)displayedStatus;
- (void)setValidationErrors:(id)arg1;
@property(readonly) NSArray *validationErrors;
@property(readonly) NSURL *applicationIconURL;
@property(copy) NSString *userProvidedComment;
@property(copy) NSString *userProvidedName;
@property(readonly) NSString *platformDisplayName;
@property(readonly) NSDate *archivedDate;
@property(readonly) NSString *applicationVersion;
@property(readonly) NSString *bundleIdentifier;
- (id)infoPlist;
@property(readonly) NSURL *containedApplicationURL;
@property(readonly) NSString *platformIdentifier;
@property(readonly) NSString *applicationName;
@property(readonly) NSURL *archiveInfoURL;
- (void)_writeArchiveInfo;
- (id)initWithContentsOfURL:(id)arg1 info:(id)arg2;

@end

