//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import <DevToolsCore/XCObjectBucket.h>

@interface XCBreakpointsBucket : XCObjectBucket
{
}

+ (BOOL)importing;
+ (void)setImporting:(BOOL)arg1;
- (id)container;
- (void)_breakpointWillBeRemoved:(id)arg1;
- (void)_breakpointWasAdded:(id)arg1;
- (void)dealloc;
- (void)purify;
- (void)listenToSource:(id)arg1 removeOnly:(BOOL)arg2;
- (void)validateAgainstProject:(id)arg1;

@end

