//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <DevToolsCore/XCPosixTask.h>

@class NSMutableString;

@interface XCBuildOperationPumpTask : XCPosixTask
{
    NSMutableString *_taskOutput;
    BOOL _isOutputCompleted;
}

@property BOOL isOutputCompleted; // @synthesize isOutputCompleted=_isOutputCompleted;
@property(retain) NSMutableString *taskOutput; // @synthesize taskOutput=_taskOutput;
- (BOOL)waitUntilOutputIsCompleted;
- (void)outputComplete;
- (void)receivedStderrObject:(id)arg1;
- (void)receivedStdoutObject:(id)arg1;
- (id)initWithLaunchInfo:(id)arg1;

@end

