//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <DevToolsCore/XCPosixTaskLaunchInfo.h>

@interface XCBuildOperationPumpTaskLaunchInfo : XCPosixTaskLaunchInfo
{
}

- (void)shutdownByUsingSystem;
- (void)shutdown;
- (id)startupByUsingSystem:(id)arg1;
- (id)startupWithDistccHosts:(id)arg1;

@end

