//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import "NSObject.h"

@class TSRegularExpression;

@interface XCBuildCommandOutputRegexParseRule : NSObject
{
    TSRegularExpression *_regex;
    int _actionCode;
}

+ (id)buildCommandOutputRegexParseRulesFromPListArrays:(id)arg1 outerKeyNameForExceptions:(id)arg2 innerKeyNameForExceptions:(id)arg3;
- (id)description;
- (BOOL)matchCommandOutputLineString:(id)arg1 logSectionRecorder:(id)arg2;
- (void)dealloc;
- (id)initWithRegularExpression:(id)arg1 actionCode:(int)arg2;

@end

