//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import <DevToolsCore/PBXBuildSettingsDictionary.h>

@class NSMutableArray, NSMutableSet;

@interface XCBuildSettingsCompositeDictionary : PBXBuildSettingsDictionary
{
    NSMutableArray *_baseDictionaries;
    NSMutableSet *_settingNamesToRecache;
    BOOL _ignoreBaseDictChanges;
}

- (void)removeBuildSettingForKeyPath:(id)arg1 conditionSet:(id)arg2;
- (void)setBuildSetting:(id)arg1 operation:(int)arg2 forKeyPath:(id)arg3 conditionSet:(id)arg4;
- (void)removeObjectForKey:(id)arg1;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (id)_buildSettings;
- (void)baseDictionaryChanged:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)initWithDictionaries:(id)arg1;
- (id)initWithArrayOfDictionaries:(id)arg1;
- (id)initWithDictionary:(id)arg1;

@end

