//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import "NSObject.h"

@class NSMutableDictionary, PBXTargetBuildContext, XCBuildableState;

@interface XCBuildStateStore : NSObject
{
    PBXTargetBuildContext *_buildContext;
    XCBuildableState *_buildableState;
    NSMutableDictionary *_nodeStatesByIdent;
    NSMutableDictionary *_commandStatesByIdent;
}

- (id)longDescription;
- (void)writeToFileHandle:(struct __sFILE *)arg1;
- (void)readFromFileHandle:(struct __sFILE *)arg1;
- (BOOL)archiveFormatVersionIsCompatible;
- (id)commandStateWithIdentifier:(id)arg1 createIfNeeded:(BOOL)arg2;
- (id)nodeStateWithIdentifier:(id)arg1 createIfNeeded:(BOOL)arg2;
- (id)buildableState;
- (id)buildContext;
- (void)dealloc;
- (id)init;
- (id)initWithBuildContext:(id)arg1;

@end

