//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import "NSObject.h"

@class XCTextFileLocation;

@interface XCBuildLogAnalyzerControlFlowStepEdge : NSObject
{
    XCTextFileLocation *_startFileLocation;
    XCTextFileLocation *_endFileLocation;
}

- (id)description;
- (void)writeToSerializer:(id)arg1;
- (id)initFromDeserializer:(id)arg1;
- (id)endFileLocation;
- (id)startFileLocation;
- (void)dealloc;
- (id)initWithStartLocation:(id)arg1 endLocation:(id)arg2;

@end

