//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import <DevToolsCore/PBXCompilerSpecificationGcc3_3.h>

@interface XCCompilerSpecificationClang : PBXCompilerSpecificationGcc3_3
{
}

- (void)addIdentifierToListOfCompilersUsedInTargetBuildContext:(id)arg1;
- (BOOL)dwarfSymbolRepositoryIsEnabledInTargetBuildContext:(id)arg1;
- (BOOL)symbolSeparationIsEnabledInTargetBuildContext:(id)arg1;
- (id)precompFileExtension;
- (id)effectiveCompilerSpecificationForFileType:(id)arg1 inPropertyExpansionContext:(id)arg2 platformDomain:(id)arg3;

@end

