//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import <DevToolsCore/XCSDKPath.h>

#import "XCPosixTaskBackgroundParsing.h"

@class NSMutableArray, NSMutableString, NSString, XCPosixTask;

@interface XCCompositeSDKPath : XCSDKPath <XCPosixTaskBackgroundParsing>
{
    NSString *_originalSDKROOT;
    NSMutableArray *_sourcePaths;
    BOOL _isCompositeSDK;
    BOOL _isUpdating;
    BOOL _ended;
    XCPosixTask *_task;
    NSString *_taskDescriptionString;
    NSMutableString *_results;
    NSMutableString *_errors;
    id _taskStatus;
    id _project;
}

- (void)taskDidTerminate:(id)arg1;
- (void)task:(id)arg1 hasSpawnStatus:(int)arg2;
- (void)task:(id)arg1 receivedStderrObjectInBackground:(id)arg2;
- (void)task:(id)arg1 receivedStdoutObjectInBackground:(id)arg2;
- (id)_errorStrippedStringForString:(id)arg1;
- (void)_rebuild;
- (long long)runMKSDK;
- (BOOL)removeCompositeSDKDirectory;
- (id)getSetTaskDescriptionString:(id)arg1;
- (void)_verify:(id)arg1;
- (BOOL)_compositeNeedsUpdating;
- (id)_getArguments;
- (void)_constructCompositeSDKPath:(id)arg1;
- (void)dealloc;
- (id)_initWithSDKString:(id)arg1 withBuildContext:(id)arg2;
- (BOOL)isCompositeSDK;
- (id)results;
- (id)errors;
- (id)project;
- (BOOL)taskStopRunning;
- (id)taskDescriptionString;
- (id)taskStatus;
- (void)setTaskStatus:(id)arg1;

@end

