//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import <DevToolsCore/PBXBuildSettingsDictionary.h>

@class XCPropertyConditionSet;

@interface XCConditionalBuildSettingsDictionary : PBXBuildSettingsDictionary
{
    XCPropertyConditionSet *_conditionSet;
}

- (BOOL)matchesConditionSet:(id)arg1;
- (id)conditionSet;
- (BOOL)isConditional;
- (id)archivedDictionaryRepresentation;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)initWithConditionSet:(id)arg1;
- (id)initWithDictionary:(id)arg1 conditionSet:(id)arg2;
- (id)initWithDictionaryNoCopy:(id)arg1;
- (void)_extractConditionalDictionaries;

@end

