//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface XCCommandLineToolInvocation : NSObject
{
    NSString *_toolIdent;
    NSDictionary *_paramDict;
    NSString *_conditionPath;
}

- (id)description;
- (id)createDependenciesInBuildContext:(id)arg1;
- (id)conditionPath;
- (id)parameterDictionary;
- (id)toolIdentifier;
- (void)dealloc;
- (id)init;
- (id)initWithPropertyListDictionary:(id)arg1;
- (id)initWithToolIdentifier:(id)arg1 parameters:(id)arg2;
- (id)initWithToolIdentifier:(id)arg1 parameters:(id)arg2 conditionPath:(id)arg3;

@end

