//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import "NSObject.h"

@class NSMutableSet, NSNumber, NSString;

@interface XCDerivedFileCachePathLockInfo : NSObject
{
    NSString *_path;
    int _lockType;
    unsigned long long _lockCount;
    NSNumber *_clientIdWithWriteLock;
    NSMutableSet *_clientIdsWhichUnlockedForWriting;
}

- (BOOL)wasUnlockedForWritingByClientId:(id)arg1;
- (unsigned long long)lockCount;
- (int)lockType;
- (void)unlockByClientId:(id)arg1;
- (BOOL)lockForType:(int)arg1 byClientId:(id)arg2;
- (void)dealloc;
- (id)initWithPath:(id)arg1;

@end

