//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import <DevToolsCore/XCDependencyCommand.h>

@interface XCDependencyShadowCommand : XCDependencyCommand
{
    XCDependencyCommand *_originalCommand;
}

- (id)description;
- (void)decrementWaitCountsOfDependingNodes;
- (void)incrementWaitCountsOfDependingNodes;
- (id)instantiatedCommandOutputParserWithLogSectionRecorder:(id)arg1;
- (id)environment;
- (id)workingDirectoryPath;
- (id)subprocessCommandLineForProcessing;
- (id)arguments;
- (id)commandPath;
- (id)ruleInfo;
- (BOOL)isReadyForProcessing;
- (id)name;
- (id)originalCommand;
- (void)dealloc;
- (id)initWithOriginalCommand:(id)arg1;

@end

