//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import "NSObject.h"

@class NSArray, NSDictionary, NSString;

@interface XCDependencyGraphValidationRule : NSObject
{
    NSString *_nodeNamePattern;
    long long _expectedNodeCount;
    NSArray *_expectedDependsPatterns;
    NSArray *_expectedIncludesPatterns;
    NSDictionary *_expectedCommandPatterns;
}

- (BOOL)performValidationsInBuildContext:(id)arg1;
- (void)dealloc;
- (id)init;
- (id)initWithPListDictionary:(id)arg1;

@end

