//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import <DevToolsCore/XCDiffDataSource.h>

@interface XCDiffMergeDataSource : XCDiffDataSource
{
    struct __CFDictionary *_updatedDescriptors;
    struct _XCDiffMergeDataSourceFlags _dmdsFlags;
}

+ (void)initialize;
- (void)diffDescriptorDidChange:(id)arg1;
- (void)diffDescriptorWillChange:(id)arg1;
- (void)appendStringForDiffDescriptor:(id)arg1;
- (void)_diffContextDidChangeDiffDescriptors:(id)arg1;
- (void)_diffContextWillChangeDiffDescriptors:(id)arg1;
- (void)setDiffContext:(id)arg1;
- (void)endEditingContent;
- (void)beginEditingContent;
- (BOOL)_setContent:(id)arg1;
- (BOOL)needsUpdate;
- (void)setNeedsUpdate:(BOOL)arg1;
- (void)dealloc;
- (id)initWithContent:(id)arg1;

@end

