//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import <DevToolsCore/XCDistributedBuildHost.h>

@class NSString;

@interface XCDistributedBuildDistccHost : XCDistributedBuildHost
{
    NSString *_distccVersion;
    NSString *_bonjourServiceName;
    long long _priority;
}

+ (id)distributedBuildHostWithSpec:(id)arg1 port:(unsigned long long)arg2;
+ (id)distributedBuildHostWithSpec:(id)arg1;
+ (id)distributedBuildHostWithSpec:(id)arg1 bonjourServiceName:(id)arg2 port:(unsigned long long)arg3;
- (long long)compare:(id)arg1;
- (long long)priority;
- (BOOL)wasDiscoveredByBonjour;
- (void)clearHostInfo;
- (void)refresh;
- (id)description;
- (id)statusString;
- (BOOL)hasSDK:(id)arg1;
- (BOOL)hasCompiler:(id)arg1;
- (void)setIsSharing:(BOOL)arg1;
- (BOOL)isCompatibleHost;
- (id)distccVersionString;
- (void)setBonjourServiceName:(id)arg1;
- (id)bonjourServiceName;
- (id)setSystemInfoFromData:(id)arg1;
- (BOOL)_processDistccError:(long long)arg1;
- (id)launchInfoForSystemInfoFetch;
- (void)dealloc;
- (id)initWithHostSpec:(id)arg1;
- (id)initWithHostSpec:(id)arg1 port:(unsigned long long)arg2;
- (id)_initWithHostSpec:(id)arg1 bonjourServiceName:(id)arg2;
- (id)_initWithHostSpec:(id)arg1 bonjourServiceName:(id)arg2 port:(unsigned long long)arg3;

@end

