//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import <DevToolsCore/XCTargetDGSnapshot.h>

@class NSString;

@interface XCExternalTargetDGSnapshot : XCTargetDGSnapshot
{
    NSString *_buildToolPath;
    NSString *_buildArgumentsString;
    NSString *_buildWorkingDirectory;
    BOOL _passBuildSettingsInEnvironment;
}

- (BOOL)passesBuildSettingsInEnvironment;
- (id)buildWorkingDirectory;
- (id)buildArgumentsString;
- (id)buildToolPath;
- (void)dealloc;
- (id)initWithInformationFromTarget:(id)arg1 withBuildState:(id)arg2;
- (void)computeDependenciesInTargetBuildContext:(id)arg1;

@end

