//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <DevToolsCore/XCOutputStream.h>

@interface XCFilterOutputStream : XCOutputStream
{
    id <XCOutputStreams> _nextOutputStream;
    BOOL _closesNextOutputStream;
}

- (void)close;
- (void)flush;
- (void)writeBytes:(const char *)arg1 length:(unsigned long long)arg2;
- (void)setClosesNextOutputStreamWhenClosed:(BOOL)arg1;
- (BOOL)closesNextOutputStreamWhenClosed;
- (id)lastOutputStream;
- (void)setNextOutputStream:(id)arg1;
- (id)nextOutputStream;
- (void)dealloc;
- (id)init;
- (id)initWithNextOutputStream:(id)arg1;

@end

