//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface XCIndexingInfo : NSObject
{
    NSString *_languageName;
    NSString *_dialectName;
    NSArray *_macroDefines;
    NSArray *_macroUndefines;
    NSArray *_quoteSearchPaths;
    NSArray *_bracketSearchPaths;
    NSArray *_systemSearchPaths;
}

- (void)dealloc;
- (id)initWithLanguageName:(id)arg1 dialectName:(id)arg2 macroDefines:(id)arg3 macroUndefines:(id)arg4 quoteSearchPaths:(id)arg5 bracketSearchPaths:(id)arg6 systemSearchPaths:(id)arg7;

@end

