//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import <DevToolsCore/PBXCCScope.h>

@class NSArray, NSMutableDictionary, NSString, PBXProjectIndex;

@interface XCJavaCCImportsScope : PBXCCScope
{
    PBXProjectIndex *_projIndex;
    NSString *_package;
    NSArray *_imports;
    NSMutableDictionary *_importsDict;
}

+ (id)importsScopeWithIndex:(id)arg1 packageName:(id)arg2 imports:(id)arg3;
- (void)addSymbolsToArray:(id)arg1;
- (id)getSymbolWithName:(id)arg1;
- (void)addSymbol:(id)arg1;
- (id)importsDict;
- (void)addDefaultPackageSymbols;
- (void)addSymbolsFromPackageDot:(id)arg1;
- (void)addClassImportWithName:(id)arg1;
- (void)addClassImport:(id)arg1;
- (id)description;
- (void)dealloc;
- (id)initWithIndex:(id)arg1 packageName:(id)arg2 imports:(id)arg3;

@end

