//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <DevToolsCore/PBXBundleProductType.h>

@interface XCKernelExtensionProductType : PBXBundleProductType
{
}

- (void)addBaseLinkerFlagsInTargetBuildContext:(id)arg1;
- (void)compileAuxiliaryFilesForVariant:(id)arg1 architecture:(id)arg2 inTargetBuildContext:(id)arg3;
- (void)defineAuxiliaryFilesInTargetBuildContext:(id)arg1;

@end

