//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import "NSObject.h"

@class NSArray, NSString;

@interface XCKeyDependencyData : NSObject
{
    NSString *_key;
    NSString *_context;
    NSArray *_keyPaths;
}

@property(copy) NSArray *keyPaths; // @synthesize keyPaths=_keyPaths;
@property(copy) NSString *context; // @synthesize context=_context;
@property(copy) NSString *key; // @synthesize key=_key;
- (void)dealloc;

@end

