//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <DevToolsCore/XCTargetDGSnapshot.h>

@interface XCNativeTargetDGSnapshot : XCTargetDGSnapshot
{
}

- (BOOL)isJambased;
- (BOOL)isNative;
- (id)initWithInformationFromTarget:(id)arg1 withBuildState:(id)arg2;
- (void)computeDependenciesInTargetBuildContext:(id)arg1;
- (BOOL)checkConsistencyOfTargetBuildContext:(id)arg1;

@end

