//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import "NSObject.h"

@class NSArray;

@interface XCObjectGraphPath : NSObject
{
    NSArray *_pathSegmentGIDs;
    NSArray *_pathSegmentNames;
}

- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)copy;
- (id)stringRepresentation;
- (id)segmentGIDAtIndex:(unsigned long long)arg1;
- (id)segmentNameAtIndex:(unsigned long long)arg1;
- (unsigned long long)segmentCount;
- (id)pathSegmentGIDs;
- (id)pathSegmentNames;
- (id)pathByAddingSegmentWithGID:(id)arg1 name:(id)arg2;
- (void)dealloc;
- (id)initWithSegmentGIDs:(id)arg1 names:(id)arg2;
- (id)init;

@end

