//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import <DevToolsCore/XCProjectRenameItem.h>

@interface XCProjectRenameFileItem : XCProjectRenameItem
{
}

- (void)validate;
- (void)renamedFileAtPath:(id)arg1 to:(id)arg2 error:(id)arg3;
- (void)rename;

@end

