//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, TSPropertyListDictionary;

@interface XCPropertyValueDefinition : NSObject
{
    NSString *_value;
    id _commandLineArgs;
    NSString *_localizedValue;
    NSString *_localizedDescription;
    TSPropertyListDictionary *_properties;
}

- (id)valueForUndefinedKey:(id)arg1;
- (id)properties;
- (id)localizedDescription;
- (id)localizedValue;
- (id)value;
- (id)commandArgumentGenerationInfo;
- (void)dealloc;
- (id)initFromPListDictionary:(id)arg1 forPropertyName:(id)arg2;

@end

