//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import <DevToolsCore/XCPropertyMacroExpression.h>

@interface XCPropertyMacroConditionalExpression : XCPropertyMacroExpression
{
    XCPropertyMacroExpression *_condExpr;
    XCPropertyMacroExpression *_thenExpr;
    XCPropertyMacroExpression *_elseExpr;
}

- (id)description;
- (BOOL)evaluateAsBooleanInContext:(id)arg1;
- (id)evaluateInContext:(id)arg1;
- (void)dealloc;
- (id)init;
- (id)initWithConditionExpression:(id)arg1 thenExpression:(id)arg2 elseExpression:(id)arg3;

@end

