//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import <DevToolsCore/XCPropertyValue.h>

@class NSArray, NSString;

@interface XCPropertyMacroExpansionValue : XCPropertyValue
{
    NSString *_prefixString;
    XCPropertyValue *_macroNameValue;
    XCPropertyValue *_suffixValue;
    NSArray *_operators;
    unsigned short _delimChar;
}

- (id)propertyValueDebugDescription;
- (id)description;
- (void)assertInternalConsistency;
- (id)evaluateAsStringInContext:(id)arg1 withNestingState:(const void *)arg2;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithPrefixString:(id)arg1 macroNameValue:(id)arg2 delimiterCharacter:(unsigned short)arg3 operators:(id)arg4 suffixValue:(id)arg5;

@end

