//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <DevToolsCore/XCWorkQueueCommandSubprocessInvocation.h>

@interface XCProductPackagingUtilityCommandInvocation : XCWorkQueueCommandSubprocessInvocation
{
}

+ (id)propertyListWithContentsOfFile:(id)arg1 format:(unsigned long long *)arg2 withError:(id *)arg3;
- (BOOL)isRunning;
- (BOOL)launchSubprocessWithArguments:(const char **)arg1 environment:(const char **)arg2 workingDirectory:(const char *)arg3;
- (BOOL)validBundleIdentifier:(id)arg1;
- (id)illegalUTICharacterSet;
- (void)_processEntitlements:(id)arg1 outputPath:(id)arg2;
- (void)_writeObject:(id)arg1 toFile:(id)arg2;

@end

