//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <DevToolsCore/XCPropertyMacroBooleanExpression.h>

@class XCPropertyMacroExpression;

@interface XCPropertyMacroBinaryBooleanExpression : XCPropertyMacroBooleanExpression
{
    XCPropertyMacroExpression *_leftExpr;
    XCPropertyMacroExpression *_rightExpr;
}

- (id)description;
- (void)dealloc;
- (id)init;
- (id)initWithLeftExpression:(id)arg1 rightExpression:(id)arg2;

@end

