//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import <DevToolsCore/XCRefactoringFileChange.h>

@class NSString;

@interface XCRefactoringTextFileChange : XCRefactoringFileChange
{
    NSString *_replacementString;
}

- (id)description;
- (BOOL)isEqualToFileChange:(id)arg1;
- (id)replacementString;
- (struct _XCRefactoringLineInfo)lineInfo;
- (void)dealloc;
- (id)initWithTextFileChangeSet:(id)arg1 textFileLocation:(id)arg2 replacementString:(id)arg3;

@end

