//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import "NSObject.h"

@class NSString, PBXExecutable;

@interface XCRemoteExecutable : NSObject
{
    BOOL shouldLaunch;
    BOOL shouldDebug;
    long long debugPort;
    PBXExecutable *localExecutable;
    NSString *localBundlePath;
    NSString *installedPath;
    NSString *executableReferencePath;
    NSString *sdkPath;
}

@property long long debugPort; // @synthesize debugPort;
@property BOOL shouldDebug; // @synthesize shouldDebug;
@property BOOL shouldLaunch; // @synthesize shouldLaunch;
@property(retain) PBXExecutable *localExecutable; // @synthesize localExecutable;
@property(retain) NSString *executableReferencePath; // @synthesize executableReferencePath;
@property(retain) NSString *installedPath; // @synthesize installedPath;
@property(retain) NSString *localBundlePath; // @synthesize localBundlePath;
@property(retain) NSString *sdkPath; // @synthesize sdkPath;

@end

