//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <DevToolsCore/XCRefactoringNibFileChange.h>

@interface XCRefactoringNibFileClassChange : XCRefactoringNibFileChange
{
}

+ (id)commandString;
- (id)destinationClass;
- (void)setDestinationClass:(id)arg1;
- (id)sourceClass;
- (void)setSourceClass:(id)arg1;

@end

