//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import <DevToolsCore/XCRefactoringNibFileChange.h>

@interface XCRefactoringNibFileActionChange : XCRefactoringNibFileChange
{
}

+ (id)commandString;
- (id)destinationActionType;
- (void)setDestinationActionType:(id)arg1;
- (id)destinationActionName;
- (void)setDestinationActionName:(id)arg1;
- (id)destinationActionClass;
- (void)setDestinationActionClass:(id)arg1;
- (id)sourceActionType;
- (void)setSourceActionType:(id)arg1;
- (id)sourceActionName;
- (void)setSourceActionName:(id)arg1;
- (id)sourceActionClass;
- (void)setSourceActionClass:(id)arg1;
- (id)initWithFileChangeSet:(id)arg1 fileLocation:(id)arg2;

@end

