//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import "NSObject.h"

@class PBXFileReference, PBXProject, XCRefactoringNewTextFileChangeSet;

@interface XCRefactoringRequestAddNewTextFileCallback : NSObject
{
    id _delegate;
    PBXProject *_project;
    XCRefactoringNewTextFileChangeSet *_newTextFileChangeSet;
    PBXFileReference *_newFileReference;
    id _callbackTarget;
    SEL _callbackSelector;
}

- (void)dealloc;
- (void)finishAddRequest:(id)arg1;
- (id)initWithDelegate:(id)arg1 project:(id)arg2 newTextFileChangeSet:(id)arg3 newFileReference:(id)arg4 callbackTarget:(id)arg5 selector:(SEL)arg6;

@end

