//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import "NSObject.h"

@interface XCRecruiterMessage : NSObject
{
    id _messageType;
    id _dictionary;
}

- (id)wireEncode;
- (id)objectForKey:(id)arg1;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (id)messageDictionary;
- (id)messageType;
- (id)initWithMessageType:(id)arg1 andContentDictionary:(id)arg2;
- (id)initWithMessageType:(id)arg1;
- (void)dealloc;
- (id)init;

@end

