//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <DevToolsCore/XCRefactoringNibFileChange.h>

@interface XCRefactoringNibFileOutletChange : XCRefactoringNibFileChange
{
}

+ (id)commandString;
- (id)destinationOutletName;
- (void)setDestinationOutletName:(id)arg1;
- (id)destinationOutletType;
- (void)setDestinationOutletType:(id)arg1;
- (id)destinationOutletClass;
- (void)setDestinationOutletClass:(id)arg1;
- (id)sourceOutletName;
- (void)setSourceOutletName:(id)arg1;
- (id)sourceOutletType;
- (void)setSourceOutletType:(id)arg1;
- (id)sourceOutletClass;
- (void)setSourceOutletClass:(id)arg1;
- (id)initWithFileChangeSet:(id)arg1 fileLocation:(id)arg2;

@end

