//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, PBXProject;

@interface XCRoots : NSObject
{
    PBXProject *_project;
    NSMutableArray *_roots;
}

- (id)absolutePathForRoot:(id)arg1;
- (id)description;
- (void)setRoots:(id)arg1;
- (id)roots;
- (void)dealloc;
- (id)initWithArray:(id)arg1 project:(id)arg2;

@end

