//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "NSObject.h"

@protocol XCSCMOperationDelegate <NSObject>
- (id)delegate;
- (void)operation:(id)arg1 reportedObject:(id)arg2 forKey:(id)arg3 forItemAtPath:(id)arg4;
- (void)operation:(id)arg1 wasSuspendedWithCode:(id)arg2 message:(id)arg3;
- (void)operation:(id)arg1 reportedError:(id)arg2;
- (void)operation:(id)arg1 reportedMessage:(id)arg2;
- (void)operation:(id)arg1 finishedParsingForItemAtPath:(id)arg2;
@end

