//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import <DevToolsCore/PBXObject.h>

#import "NSCopying.h"

@class NSArray, NSDictionary, NSString;

@interface XCSCMLog : PBXObject <NSCopying>
{
    NSString *_filePath;
    NSString *_headRevision;
    NSString *_activeBranchTag;
    NSDictionary *_tagsToRevisions;
    NSArray *_revisions;
}

- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)revisionAtIndex:(unsigned long long)arg1;
- (id)revisionForTag:(id)arg1;
- (id)tagsForRevision:(id)arg1;
- (void)_setRevisions:(id)arg1;
- (id)revisions;
- (void)_setTagsToRevisions:(id)arg1;
- (id)tagsToRevisions;
- (void)_setActiveBranchTag:(id)arg1;
- (id)activeBranchTag;
- (void)_setHeadRevision:(id)arg1;
- (id)headRevision;
- (void)_setFilePath:(id)arg1;
- (id)filePath;
- (id)innerDescription;
- (void)dealloc;
- (id)init;
- (id)initWithFilePath:(id)arg1 headRevision:(id)arg2 activeBranchTag:(id)arg3 tagsToRevisions:(id)arg4 revisions:(id)arg5;

@end

