//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, SCMSandboxEntry;

@interface XCSCMInfo : NSObject
{
    SCMSandboxEntry *_sandboxEntry;
    NSMutableDictionary *_scmProperties;
}

- (id)description;
- (id)sandboxEntry;
- (BOOL)hasMoreInterestingInfoThan:(id)arg1;
- (id)_refSCMStatusString;
- (id)scmStateString;
- (id)scmStateShortString;
- (void)clear;
- (void)setSandboxEntry:(id)arg1;
- (void)setProperties:(id)arg1;
- (id)scmProperties;
- (void)setLog:(id)arg1;
- (id)scmObjectForKey:(id)arg1;
- (void)sendStateChangeNotificationForReference:(id)arg1 inProject:(id)arg2;
- (void)printSCMProperties;
- (void)dealloc;
- (id)initWithSandboxEntry:(id)arg1;

@end

