//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import "NSObject.h"

#import "XCApplicationArchiver.h"

@class DTExtension, NSArray, XCPlatformSpecification;

@interface XCSimpleApplicationArchiver : NSObject <XCApplicationArchiver>
{
    XCPlatformSpecification *_platform;
    DTExtension *_extension;
}

@property(retain) DTExtension *extension; // @synthesize extension=_extension;
@property(retain) XCPlatformSpecification *platform; // @synthesize platform=_platform;
- (Class)detailViewControllerClass;
- (id)applicationIconURL;
- (_Bool)archiveApplicationAtURL:(id)arg1 error:(id *)arg2;
- (_Bool)willWriteArchiveInfo:(id)arg1 forApp:(id)arg2 error:(id *)arg3;
- (id)initWithExtension:(id)arg1;

// Remaining properties
@property(readonly) NSArray *actionNames;

@end

