//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import "NSObject.h"

@class NSMutableArray;

@interface XCSpecificationFilter : NSObject
{
    Class _specClass;
    BOOL _emptyFilterIncludesAll;
    NSMutableArray *_includedSpecs;
    NSMutableArray *_excludedSpecs;
}

- (id)description;
- (BOOL)includesSpecification:(id)arg1;
- (BOOL)includesAnySpecifications;
- (BOOL)includesAllSpecifications;
- (void)addExcludedSpecificationComposition:(id)arg1;
- (void)addIncludedSpecificationComposition:(id)arg1;
- (void)removeExcludedSpecification:(id)arg1;
- (void)addExcludedSpecification:(id)arg1;
- (void)addExcludedSpecifications:(id)arg1;
- (id)excludedSpecifications;
- (void)removeIncludedSpecification:(id)arg1;
- (void)addIncludedSpecification:(id)arg1;
- (void)addIncludedSpecifications:(id)arg1;
- (id)includedSpecifications;
- (void)_addSpecification:(id)arg1 toList:(id)arg2;
- (void)dealloc;
- (id)init;
- (id)initWithSpecificationClass:(Class)arg1;
- (id)initWithSpecificationClass:(Class)arg1 emptyFilterIncludesAll:(BOOL)arg2;

@end

