//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import <DevToolsCore/XCOperation.h>

@class NSThread, XCMessageQueue;

@interface XCThreadedOperation : XCOperation
{
    XCMessageQueue *_messageQueue;
    NSThread *_runningThread;
}

- (void)sendDataToOutputStreamInOriginatingThread:(id)arg1;
- (void)performInvocationInOriginatingThread:(id)arg1;
- (void)postNotificationInOriginatingThread:(id)arg1;
- (void)setMessageDispatchSuspended:(BOOL)arg1;
- (void)handleAvailableObjectsOnMessageQueue:(id)arg1;
- (void)decodeOutputData:(id)arg1;
- (int)cleanupAfterRunning;
- (void)_runOperationInBackground;
- (int)runOperationInBackground;
- (int)runOperation;
- (int)setupBeforeRunning;
- (id)runningThread;
- (void)finalize;
- (void)dealloc;
- (id)initWithIdentifier:(id)arg1;

@end

