//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Jan  8 2013 19:10:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode5-DP6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
//

#import "NSObject.h"

@class NSArray, NSDictionary, NSMutableDictionary, NSSet, XCFnmatchPatternSet;

@interface XCToolSpecification_ivars : NSObject
{
    NSArray *commandLineTemplate;
    XCFnmatchPatternSet *patternsOfFlagsToElide;
    NSArray *ruleLineTemplate;
    Class commandInvocationClass;
    NSArray *outputParserClassesOrRules;
    Class resultsPostprocessorClass;
    NSArray *fallbackToolIdentifiers;
    NSMutableDictionary *fallbackToolSpecifications;
    NSSet *inputFileTypes;
    NSArray *additionalPathsToClean;
    XCFnmatchPatternSet *flagsNotAffectingOutputFile;
    BOOL supportsDeploymentTarget;
    NSMutableDictionary *defaultDeploymentTargetsByName;
    NSArray *outputPaths;
    BOOL outputsAreProducts;
    NSDictionary *environmentVariables;
    NSArray *requiredComponents;
    BOOL shouldSynthesizeGlobalBuildRule;
    NSArray *buildPhasesForWhichToSynthesizeBuildRules;
}

- (void)dealloc;

@end

